### ISSUE TITLE
Windows Compiling Problem

### ISSUE THREAD

**Issue by rafaeloledo** [velascoandres/drawy#29]
![image](https://github.com/velascoandres/drawy/assets/51183852/e50cafde-d25e-4144-9891-57baa8e95231)
Running the cargo command gives this in Windows
Linux is compiling fine
Any idea?
I have sqlite installed with scoop and stable rust set with rustup

Edit 6/10/2024 7:30 PM UTC-3: I found this gist, going to test and see if it works. It seems that, of course, `sqlite` lib files are a separate installation. https://gist.github.com/zeljic/d8b542788b225b1bcb5fce169ee28c55

**Comment by Krb0** [comment]
@velascoandres any suggestions?

**Comment by velascoandres** [comment]
You should probably have the path to sqlite correctly defined in your env vars on windows

**Comment by rafaeloledo** [comment]
It's trying to open sqlite3.lib, my `scoop` installation doesn't come it with. I don't have experience with having sqlite lib files. Here's the tree. Original `sqlite` installation comes with the lib files?

```
.
├── 3.46.0
│  ├── install.json
│  ├── manifest.json
│  ├── sqldiff.exe
│  ├── sqlite3.exe
│  └── sqlite3_analyzer.exe
└── current -> C:\dev\scoop\apps\sqlite\3.46.0
```
